### ISSUE TITLE
Meteye?

### ISSUE THREAD

**Issue by mlava** [carlhako/weatherfeed#1]
Hi there,
Is there any possibility to update / modify this to use the Meteye service?
For example, http://www.bom.gov.au/places/qld/brisbane/

Thanks for advice!

**Comment by carlhako** [comment]
Hi I've actually re written most of this to use the boms api which I did not know existed. I'll check out that meteye link. What data do you want available from this service specifically?

**Comment by mlava** [comment]
I also didn't know about their API.
I want to wrap your code in a ninja-block driver to give my ninja-block
access to up-to-date local weather.
I'd love to be able to use the chance of rain, significant weather warnings
etc
I have done so for the forecast.io api (https://github.com/mlava/ninja-forecast), but I find their predictions not as accurate in Australia.
NB uses node.js (for now) so your code seemed a perfect fit!
Cheers

NB. data from the detailed forecast would be even better! eg. http://www.bom.gov.au/places/qld/brisbane/forecast/detailed/

I'm happy to help if you like: do you have your new code on github?

**Comment by carlhako** [comment]
Ill fix it up and post it tonight (using their api)
meteye looks pretty good and so does that detailed forecast. Ill have a go at scraping them as well and let you know.

I am using this data to display on an lcd screen controlled via an arduino and esp8266. Hence the TCP server makes it easy to fetch the data and just dump the exact string onto the LCD rather then try to manipulate it in c++.

**Comment by carlhako** [comment]
Have updated to use the API 
started working on scraping the detailed forecast using cheerio. While I can make jquery return what I want in the console of google chrome dev tools I cant replicate it using cheerio. Im almost there just need to fiddle with it a bit more. code is in bomscraper.js down the bottom. to hit the function send your browser to http://nodeserverip:5001/forecastDetailed

I will update this issue once I get somewhere with it.

**Comment by carlhako** [comment]
data now scraped from http://www.bom.gov.au/places/qld/townsville/forecast/detailed/
you just need to update the url in bomscraper.js line 32 to reflect your location.
please try it out and let me know if you have any issues.

I will update the readme now with a bit of a description.

**Comment by mlava** [comment]
thanks
initial glance suggests working well
will play more and get back to you
thanks again!

**Comment by carlhako** [comment]
im changing the object layout that is returned. its a bit hard to calculate todays date on an arduino without an rts. will probably return an array, index 0 being today.

**Comment by carlhako** [comment]
finished doing some updates, will probably leave the code be for a bit now while I now work on getting that data to the arduino and onto an lcd screen. 

How did you go with your ninja-block and what exactly does it do? I tried googling it and from what I could tell its some sort of home automation device? interesting...

**Comment by mlava** [comment]
Haven't had a chance to try yet, sorry.
Seems like it should be easy to get the data from your code and into my
ninja block, but just need some time at a computer!
I'll let you know once I have something working.
Thanks!
